version: '3.9'
services:
  db:
    image: mysql:8.3
    container_name: be_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_DATABASE: ${DB_NAME:-be}
      MYSQL_USER: ${DB_USERNAME:-beuser}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
    command: ["--default-authentication-plugin=mysql_native_password", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: be_redis
    restart: unless-stopped
    command: ["redis-server"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  be:
    build: .
    container_name: be_app
    restart: unless-stopped
    depends_on:
      - db
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_URL: jdbc:mysql://db:3306/${DB_NAME:-be}?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      DB_USERNAME: ${DB_USERNAME:-beuser}
      DB_PASSWORD: ${DB_PASSWORD:-password}
      MAIL_HOST: ${MAIL_HOST:-smtp.gmail.com}
      MAIL_PORT: ${MAIL_PORT:-587}
      MAIL_USERNAME: ${MAIL_USERNAME:-}
      MAIL_PASSWORD: ${MAIL_PASSWORD:-}
      JWT_SECRET: ${JWT_SECRET:-change_me_to_strong_secret}
      JWT_EXPIRATION_MS: ${JWT_EXPIRATION_MS:-18000000}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD:-}
      REDIS_SSL: "false"
      UPLOAD_BASE_PATH: /data/uploads
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID:-}
      PAYOS_CLIENT_ID: ${PAYOS_CLIENT_ID:-}
      PAYOS_API_KEY: ${PAYOS_API_KEY:-}
      PAYOS_CHECKSUM_KEY: ${PAYOS_CHECKSUM_KEY:-}
      PAYOS_RETURN_URL: ${PAYOS_RETURN_URL:-http://localhost:8080/api/orders/payment/payos/return}
      PAYOS_CANCEL_URL: ${PAYOS_CANCEL_URL:-http://localhost:8080/api/orders/payment/payos/cancel}
      LLM_BASE_URL: ${LLM_BASE_URL:-https://openrouter.ai/api/v1/chat/completions}
      LLM_API_KEY: ${LLM_API_KEY:-}
      LLM_MODEL: ${LLM_MODEL:-openai/gpt-3.5-turbo}
      LLM_SITE: ${LLM_SITE:-http://localhost:3000}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS:-http://localhost:3000}
    ports:
      - "8080:8080"
    volumes:
      - uploads:/data/uploads

volumes:
  db_data:
  redis_data:
  uploads:


